### ISSUE TITLE
Cross build for Scala 2.11 and 2.12

### ISSUE THREAD

**Issue by cory-p-oncota** [clulab/processors#122]
Currently the library is unusable in Scala 2.12 due to the dependency on scala-parser-combinators.

The examples here demonstrate how to cross build for scala core modules:
https://github.com/scala/scala-module-dependency-sample

**Comment by dispalt** [comment]
You mind if I take a shot at this?

**Comment by MihaiSurdeanu** [comment]
Go for it.
Thanks!

**Comment by hickst** [comment]
Closed by pull request #213

**Comment by hickst** [comment]
Cross compilation does not work: Scala 2.11 ForkJoin code has been obsoleted in 2.12 in favor of Java ForkJoin code. This breaks cross-compilation.

Since processors has been updated to use Scala 2.12, I recommend that we do not maintain a separate 2.11 version unless we have demonstrable need for it. Recommend we change the status of this issue to `WON'T FIX` and re-close it.

**Comment by myedibleenso** [comment]
@hickst, it looks like this is only an issue in the `learning` package.  Can we not cross-compile the other subprojects for 2.11?  Spark is incompatible with 2.12, so we are stuck using ancient releases.

**Comment by MihaiSurdeanu** [comment]
Thanks @marcovzla!
I will release processors next.
