### ISSUE TITLE
Code does not compile in IntelliJ

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#369]
These 2 lines of code compile Ok from the cmd line, but they do not compile in IntelliJ:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/sequences/LstmUtils.scala#L612

**Comment by kwalcock** [comment]
Have you changed branches on (out from under) IntelliJ recently?  The command line sometimes works better because it caches less.  IntelliJ monitors the main build.sbt, but doesn't seem to notice changes in build.sbt for subprojects like processors-main.  If dependencies of a subproject have changed, IntelliJ will not notice and be using the wrong jar file for the dependency which can prevent compilation.  When I suspect this happening, I edit the main build.sbt to alert IntelliJ to rebuild everything and notice changes to subprojects.  That usually fixes the problem.  It's compiling for me, so I have to suspect this kind of problem.  HTH.

**Comment by MihaiSurdeanu** [comment]
This didn't seem to fix it. 
Does the project compile in IntelliJ for you?

**Comment by kwalcock** [comment]
Yes.  I didn't notice any problem.  However, I will download a clean version into a new IntelliJ project just in case.  The link seemed to be to the master branch, so that was what I used.

**Comment by kwalcock** [comment]
It builds with no errors for me, just one deprecation warning.  IntelliJ 2019.3, FWIW.  Can you look at the External Libraries node in the Project tree and see if it is finding the right versions?

**Comment by MihaiSurdeanu** [comment]
I went pandemic on IntelliJ. After I deleted the .idea directory, things were back to normal. 
The external libraries indicated that it was using an incorrect version. But reloading the build file did not fix it.
