### ISSUE TITLE
METAL NER wiki page and an error from the config files params

### ISSUE THREAD

**Issue by vikas95** [clulab/processors#403]
Hi,

I am unable to find the Wiki page which had the METAL NER details. Is it moved to any other location ?

While training the NER model, I get this error:

[error] (run-main-0) java.lang.RuntimeException: ERROR: parameter mtl.numberOfTasks must be defined!
[error] java.lang.RuntimeException: ERROR: parameter mtl.numberOfTasks must be defined!

I am using the default the config file - "org/clulab/metal-en-ner.conf" and the numberOfTasks is set to 1. 

Thanks.

**Comment by MihaiSurdeanu** [comment]
Yes, it’s here:
http://clulab.github.io/processors/

It may be that Metal does not find your config file. Try to put it
under main/src/main/resources/org/clulab/, and call use
org/clulab/<your-conf-file> in the cmd line.


On June 28, 2020 at 1:06:06 AM, Vikas Yadav (notifications@github.com)
wrote:

Hi,

I am unable to find the Wiki page which had the METAL NER details. Is it
moved to any other location ?

While training the NER model, I get this error:

[error] (run-main-0) java.lang.RuntimeException: ERROR: parameter
mtl.numberOfTasks must be defined!
[error] java.lang.RuntimeException: ERROR: parameter mtl.numberOfTasks must
be defined!

I am using the default the config file - "org/clulab/metal-en-ner.conf" and
the numberOfTasks is set to 1.

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/issues/403>, or unsubscribe
