### ISSUE TITLE
(maybe) dumb question

### ISSUE THREAD

**Issue by BeckySharp** [clulab/processors#415]
What do you think about having something on the main README landing page that states the current stable release? 
At the moment, when I want to sync I feel like I need to go to version.sbt and subtract and hope I got it right...
That said -- that process isn't hard, just awkward :)

**Comment by MihaiSurdeanu** [comment]
Agree. @kwalcock: once the release completes, can you please add a sentence on this to the README?

**Comment by kwalcock** [comment]
I'm not sure whether I can distinguish between stable and otherwise.  There
is probably a way to indicate with an icon like the builld|passing one
already there which is the most recent version sent to maven or at least
tagged.  Otherwise I would check those tags, but that's because they show
up right away in IDEs.  I'll look for that icon/image.
