### ISSUE TITLE
LexiconNER caseInsensitivity thoughts

### ISSUE THREAD

**Issue by BeckySharp** [clulab/processors#448]
I think it would be cool if there could be different options for the `caseInsensitiveMatching` for the different lexicons involved in a LexiconNER.  This came up recently with a project in which the first 2 lexicons were caseInsensitive but then we had issues with an Actor lexicon where case did matter.  I solved it with a local wrapper, where i essentially made one LexiconNER for each lexicon and merged manually myself, but that's a shame bc that's something the LexiconNER class does well already.

perhaps something could change here? https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/sequences/LexiconNER.scala#L245

If you want, I can try to do it -- else maybe someone else -- I would imagine a constructor that took a parallel list of Boolean and also another that took a single boolean and repeated it as many times as there are lexicons to maintain the simpler current API/functionality.

ping @MihaiSurdeanu @kwalcock

**Comment by MihaiSurdeanu** [comment]
@BeckySharp: I agree! This sounds like a useful feature.
@kwalcock: do you want to do it, or should I?

**Comment by kwalcock** [comment]
I see Fast and Slow stuff there which makes me think that I had something to do with it, and I vaguely recall some issue about case and that if it was set once somewhere that everything had to match or something.  I should look at that and see if there is some limitation hiding.

**Comment by MihaiSurdeanu** [comment]
Yep. Slow is mine and Fast is yours :)
Please let me know.

**Comment by kwalcock** [comment]
I'm slowly recalling and observing that one way that this was made faster was to put all the words into a single structure from which to look them up.  One didn't have to look through all the different matchers separately.  This worked really well when the case sensitivity had a single value.  If it can have a different value, then there will likely need to be two different structures for the two possibilities, and that will slow things down a little, but so be it.  There will be some coding to do.

**Comment by MihaiSurdeanu** [comment]
I think it's worth it.
Thanks!

**Comment by kwalcock** [comment]
FWIW this line (https://github.com/clulab/processors/blob/012a80c77e042efc591b08cb4dc28353e60e7ee0/main/src/main/scala/org/clulab/sequences/LexiconNER.scala#L112) seems to be wrong.  It is the number of spaces for the entire (non-empty) array of words rather than the slice.

This `scanText` seems to be used primarily in the nearby `contentfulSpan`, which only needs to know if some of these kinds of characters exist, not their exact count.  I'm probably going to want to change things like `digits > 0` to `hasDigits`.

**Comment by MihaiSurdeanu** [comment]
Good catch! It should be: end - start - 1, no?

**Comment by kwalcock** [comment]
...and probably a `math.max()` for good measure.

**Comment by kwalcock** [comment]
How should case insensitivity be handled for the override KBs?

For the sequence of regular KBs, there is in the new version a parallel sequence of caseInsensitive Booleans.  That is fairly straightforward.  Each matcher will have its own case sensitivity value, rather than how it was done previously with one value for the entire NER.

The override KBs are specified with a sequence of files, but these aren't mapped directly to matchers.  Instead, within the files are lines and on each line the name of a matcher is specified.  These names may be in any and multiple of the files and if the case sensitivity is set per file, we can get a matcher that is one time case sensitive and one time not.  I could do that, have two matchers per name.  Maybe the sensitivity should be set in the files instead of passed as an argument (maybe even for the regular KBs).  Perhaps it needs to be set per line.  A list of all possible matchers and their case sensitivities could be provided from the start rather letting it have anything to do with the files.  Etc.

I need an opinion from someone who has used this.  Thanks!

**Comment by MihaiSurdeanu** [comment]
Can you give me an example of the override KB to refresh my memory?
I think I implemented that but it's been a while.

**Comment by kwalcock** [comment]
I don't see a good file, but this may explain it:

```scala
        if (!line.startsWith("#")) { // skip comments starting with #
          val blocks = line.split("\t")
          if (blocks.size >= 2) {
            val entity = blocks.head // grab the text of the named entity
            val label = blocks.last // grab the label of the named entity
            val tokens = entity.split("\\s+")
            // TODO: But the label needs to be mapped to case sensitivity or not.
            val matcher = matchers.getOrElseUpdate(label, new BooleanHashTrie(label))

            buildState.addWithLexicalVariations(matcher, tokens, caseInsensitive)
          }
        }
```

**Comment by MihaiSurdeanu** [comment]
I see. I think the override KB should inherit the case sensitivity of the matcher indicated in the corresponding line. I can't think of a case where they would be different...

**Comment by kwalcock** [comment]
If I recall and understand this code correctly, there is nothing that enforces the idea that the label on a line in an overrideKB has any relation to the name of a regularKB.  I don't know if it would work practically to use the case sensitivity value of the corresponding regularKB.  Would I print a lot of messages saying that there is no regularKB corresponding to the overrideKB?  Should there be a default value for the sensitivity for the cases that there isn't a match?  Is part of the reason for the override that the case sensitivity of the regularKB is incorrect for certain words?  Should there be a check that a word in the overrideKB is also present in the regularKB and therefore indeed overriding something?

**Comment by kwalcock** [comment]
@BeckySharp, I think you used this kind of functionality recently in a GazetteerEntityFinder.  It doesn't look like you used an override KB, but instead changed the case sensitivity of an entire KB, possibly on account of a single word.  Would the other option have been to place the exception in an override KB and set the sensitivity differently in that one?  The NER code is very generic and a lot depends on how it is used, so I'm looking for examples.

**Comment by MihaiSurdeanu** [comment]
I propose the following:
- If there is a regular KB that matches the label in the override KB, use the case sensitivity from that.
- If not, backoff to a case sensitivity assigned to unknown types.

**Comment by BeckySharp** [comment]
I recently wanted a case sensitive matching for the actor lexicon (because
actor names like Lean when lower case are just words).  The lexicon is too
large to remove all the ambiguous ones easily... though maybe with a dict
lookup, but that’s neither here nor there :) I don’t think Ive ever used an
override KB

**Comment by kwalcock** [comment]
I haven't used one either, but that seems like just the thing.  They are consulted first and adding the one word might do it.  However, the override part is more the change of case sensitivity, not the label, I guess.

**Comment by kwalcock** [comment]
This is in the testing phase now.

**Comment by kwalcock** [comment]
See #456
