### ISSUE TITLE
Load different languages

### ISSUE THREAD

**Issue by JavieerCG** [clulab/processors#56]
How can I run it with the Spanish model that provides the Stanford CoreNLP? 
Is it possible? Because it automatically load the English one.

Thanks

**Comment by MihaiSurdeanu** [comment]
Sorry, we don't support other languages for now.

**Comment by algui91** [comment]
Will you consider adding it? I need spanish models. If you can give me some hints, I could try to implement spanish into `processors`.

Best regards!

**Comment by MihaiSurdeanu** [comment]
We are considering adding it, but it's in our top priorities at the moment...
If you want to work on it, it's probably not too bad since CoreNLP already supports Spanish for most components: http://stanfordnlp.github.io/CoreNLP/

You have to change a few methods in org.clulab.processors.shallownlp.ShallowNLPProcessor. In particular, all the methods at the top of the class that start with "mk", such as "mkNer". All these would have to be converted to load the Spanish models instead of English.

**Comment by algui91** [comment]
Ok, Thank you, I am going to try.

**Comment by LenCewa** [comment]
Hello,

I run into the same problem. I posted [my question](http://stackoverflow.com/questions/41020551/how-to-extract-nouns-from-a-german-text-with-the-stanfordnlp-tool-in-scala) on Stack Overflow. Is it possible to run the NLP on German texts?

**Comment by MihaiSurdeanu** [comment]
Unfortunately, today we only support English.
However, CoreNLP does support Spanish and German. I recommend their SimpleCoreNLP tool:
http://stanfordnlp.github.io/CoreNLP/simple.html
