### ISSUE TITLE
Using this library puts the entire project into debug logging mode. 

### ISSUE THREAD

**Issue by hsyed** [clulab/processors#7]
Just adding this as a dependency causes all my libraries to begin spewing debug output. I suggest altering the defaults to : 
1. Disable debug as default.
2. Only make config changes for logging to your own library instead of changing the globals.

**Comment by kwalcock** [comment]
Documentation for [slf4f](https://www.slf4j.org/manual.html) states,

"Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding/provider [like logback-classic] but only depend on slf4j-api. When a library declares a transitive dependency on a specific binding, that binding is imposed on the end-user negating the purpose of SLF4J. Note that declaring a non-transitive dependency on a binding, for example for testing, does not affect the end-user."

Processors and other CLU Lab projects usually have numerous apps that are run straight from `stb`, so we want any logging they are programmed with to be active.  This works best by declaring logback as a libraryDependency.  However, we don't want that dependency to appear in the release so that whoever uses the project as a library isn't forced to use logback.  As far as I can tell, `sbt` has no built-in method of doing this, so I made one in #653.  It should be merged soon and eventually appear in a release 8.5 years after the issue was filed.

**Comment by MihaiSurdeanu** [comment]
Very nice! Thanks @kwalcock!

**Comment by kwalcock** [comment]
#653 takes care of the published POM file.  It would be nice to take care of the locally published ivy.xml as well.  Several other clulab projects should be updated as well.
